---

- name: Set up users
  user: name={{item.name}} groups=wheel,users
  with_items: users

- name: set up authorized_keys
  authorized_key: "user={{item.0.name}} key='{{ lookup('file', item.1) }}'"
  with_subelements:
    - users
    - keys

- name: setup sudo
  lineinfile: >
    dest=/etc/sudoers
    state=present
    regexp='^%wheel ALL\='
    line='%wheel ALL=(ALL) NOPASSWD:ALL'
    validate='visudo -cf %s'
